import type { EndpointCapability } from '@/lib/types';

export const ENDPOINT_CAPABILITIES: EndpointCapability[] = [
  {
    id: 'public-profile-page',
    adapter: 'publicProfileAdapter',
    method: 'GET',
    host: 'www.tiktok.com',
    path: '/@{username}',
    identifier: 'username',
    status: 'enabled',
    productionEnabled: true,
    successCondition: 'HTTP 200 HTML containing supported TikTok rehydration data',
    targetValidation: 'Extracted uniqueId/unique_id must exactly match the requested username',
    evidence: 'Page-data capture ledger plus maintained TikTok web clients',
    note: 'Default no-login profile lookup. No TikTok account, cookie, or customer credential is required.',
  },
  {
    id: 'public-video-page',
    adapter: 'publicAwemeAdapter',
    method: 'GET',
    host: 'www.tiktok.com',
    path: '/@{username}/video/{aweme_id}',
    identifier: 'aweme_id and optional username',
    status: 'enabled',
    productionEnabled: true,
    successCondition: 'HTTP 200 HTML containing an exact itemStruct/ItemModule candidate',
    targetValidation: 'Item ID must equal the requested Aweme ID; URL username is checked when returned',
    evidence: 'Page-data capture ledger and public TikTok video-page behavior',
    note: 'Default no-login video URL lookup, with the modern mobile target-feed as a fallback.',
  },
  {
    id: 'modern-aweme-feed-target',
    adapter: 'publicAwemeAdapter',
    method: 'OPTIONS',
    host: 'api16-normal-useast5.tiktokv.us',
    path: '/aweme/v1/feed/',
    identifier: 'aweme_id',
    status: 'enabled',
    productionEnabled: true,
    successCondition: 'HTTP success, TikTok status_code === 0, parseable aweme_list',
    targetValidation: 'Search every aweme_list item for an exact decimal-string aweme_id match',
    evidence: 'Controlled 100-ID replay: 100 status-0 envelopes, 79 exact hits, 21 target misses',
    note: 'Unauthenticated fixed-host request. A status-0 envelope without the requested Aweme is target_missing, not success.',
  },
  {
    id: 'modern-profile-by-id',
    adapter: 'publicProfileAdapter',
    method: 'GET',
    host: 'api16-normal-c-useast1a.tiktokv.com',
    path: '/tiktok/user/profile/other/v1',
    identifier: 'user_id',
    status: 'experimental',
    productionEnabled: true,
    successCondition: 'HTTP success and a parseable profile object inside the response component tree',
    targetValidation: 'A returned id/uid must exactly equal the requested user ID',
    evidence: 'Recent public source implementation in vit4Ss/ApiDemo; current compatibility requires probing',
    note: 'No-login numeric-ID lookup. It is enabled but visibly labeled experimental because this request family is less stable.',
  },
  {
    id: 'web-profile-posts',
    adapter: 'webPostsAdapter',
    method: 'GET',
    host: 'www.tiktok.com',
    path: '/api/post/item_list/',
    identifier: 'secUid',
    status: 'evidence-only',
    productionEnabled: false,
    successCondition: 'statusCode/status_code success and itemList envelope',
    targetValidation: 'Each returned item author must belong to the requested profile',
    evidence: 'Live read-only browser captures and maintained web clients',
    note: 'Documented next adapter. It needs a fresh complete browser-shaped signed query per page.',
  },
  {
    id: 'web-followers',
    adapter: 'followersAdapter',
    method: 'GET',
    host: 'www.tiktok.com',
    path: '/api/user/list/?scene=67',
    identifier: 'secUid',
    status: 'evidence-only',
    productionEnabled: false,
    successCondition: 'TikTok success with userList and endpoint-specific cursors',
    targetValidation: 'Preserve the requested secUid and validate the relation envelope',
    evidence: 'Live read-only browser capture',
    note: 'No customer login is inherently required, but a current signed browser request envelope is still needed.',
  },
  {
    id: 'web-following',
    adapter: 'followingAdapter',
    method: 'GET',
    host: 'www.tiktok.com',
    path: '/api/user/list/?scene=21',
    identifier: 'secUid',
    status: 'evidence-only',
    productionEnabled: false,
    successCondition: 'TikTok success with userList and endpoint-specific cursors',
    targetValidation: 'Preserve nested user/stats objects and the requested secUid',
    evidence: 'Live read-only browser capture',
    note: 'Separate from followers because the scene value and pagination semantics differ.',
  },
  {
    id: 'web-comments',
    adapter: 'commentsAdapter',
    method: 'GET',
    host: 'www.tiktok.com',
    path: '/api/comment/list/',
    identifier: 'aweme_id',
    status: 'evidence-only',
    productionEnabled: false,
    successCondition: 'TikTok success with comments, cursor, has_more, and optional total',
    targetValidation: 'Displayed comments must belong to the requested Aweme where aweme_id is supplied',
    evidence: 'Live read-only browser capture and maintained web clients',
    note: 'Exact route is known; signed request construction is intentionally not faked.',
  },
  {
    id: 'web-related',
    adapter: 'relatedAdapter',
    method: 'GET',
    host: 'www.tiktok.com',
    path: '/api/related/item_list/',
    identifier: 'itemID',
    status: 'evidence-only',
    productionEnabled: false,
    successCondition: 'TikTok success and nonempty itemList',
    targetValidation: 'Generate a fresh signature for the exact itemID; never modify a captured signed URL',
    evidence: 'Live browser capture; replay reported unstable when target changed',
    note: 'Related results are recommendations, not the requested target itself.',
  },
  {
    id: 'web-story-user-list',
    adapter: 'storyAdapter',
    method: 'GET',
    host: 'www.tiktok.com',
    path: '/api/story/user_list/',
    identifier: 'cursor and storyFeedScene',
    status: 'evidence-only',
    productionEnabled: false,
    successCondition: 'TikTok success with storyUsers and cursor state',
    targetValidation: 'A videoCount change is only a signal; resolve an exact Story item before claiming a result',
    evidence: 'Live verified and repeatedly replayed in the supplied endpoint ledger',
    note: 'Read-only Story evidence exists; the old “Story unsupported” claim was incorrect.',
  },
  {
    id: 'web-story-item-list',
    adapter: 'storyAdapter',
    method: 'GET',
    host: 'www.tiktok.com',
    path: '/api/story/item_list/',
    identifier: 'authorId',
    status: 'evidence-only',
    productionEnabled: false,
    successCondition: 'TikTok success with exact author Story items',
    targetValidation: 'Validate author ID and each returned Story item independently',
    evidence: 'Controlled replay in the supplied endpoint ledger',
    note: 'Read-only. Story view reporting is a separate state-changing route and remains disabled.',
  },
  {
    id: 'webcast-anchor-region',
    adapter: 'regionAdapter',
    method: 'GET',
    host: 'webcast16-normal-c-alisg.tiktokv.com',
    path: '/webcast/gtm/common/indicator',
    identifier: 'anchor_id',
    status: 'evidence-only',
    productionEnabled: false,
    successCondition: 'HTTP success with data.data.data.anchor_region',
    targetValidation: 'Return the field only for the requested anchor_id request',
    evidence: 'vit4Ss/ApiDemo request and response mapping',
    note: 'The value is Webcast anchor region, not a universal locked/signup country.',
  },
  {
    id: 'legacy-profile-by-id',
    adapter: 'profileAdapter',
    method: 'GET',
    host: 'api2.musical.ly',
    path: '/aweme/v1/user/',
    identifier: 'user_id',
    status: 'experimental',
    productionEnabled: false,
    successCondition: 'HTTP success, status_code === 0, user object present',
    targetValidation: 'user.uid must exactly match the requested user ID',
    evidence: 'Archived TikTok 9.1.0-era source',
    note: 'Retained only as an optional operator-signed legacy mode; it is not the default product path.',
  },
  {
    id: 'legacy-user-search',
    adapter: 'profileAdapter',
    method: 'GET',
    host: 'api2.musical.ly',
    path: '/aweme/v1/discover/search/',
    identifier: 'keyword',
    status: 'experimental',
    productionEnabled: false,
    successCondition: 'HTTP success, status_code === 0, user_list present',
    targetValidation: 'user_info.unique_id must exactly match the requested username',
    evidence: 'Archived TikTok 9.1.0-era source',
    note: 'Legacy-only; public-live username lookup uses the current TikTok profile page instead.',
  },
  {
    id: 'legacy-aweme-detail',
    adapter: 'awemeAdapter',
    method: 'GET',
    host: 'api2.musical.ly',
    path: '/aweme/v1/aweme/detail/',
    identifier: 'aweme_id',
    status: 'experimental',
    productionEnabled: false,
    successCondition: 'HTTP success, status_code === 0, aweme_detail present',
    targetValidation: 'aweme_detail.aweme_id must exactly match the requested ID',
    evidence: 'Archived TikTok 9.1.0-era source',
    note: 'Legacy-only; public-live uses current page data and the modern target-feed.',
  },
];
